import JSZip from 'jszip';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

async function createStandardDefaultZipBuild() {
  const zipPath = path.join(rootDir, 'android-app-build.zip');
  const apkPath = path.join(rootDir, 'app-release.apk');

  const apkZip = new JSZip();
  const manifestXml = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.web2apk.app">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="Web2APK"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Web2APK">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`;

  apkZip.file('AndroidManifest.xml', manifestXml);
  apkZip.file('assets/config.json', JSON.stringify({ app: 'Web2APK', version: '1.0.0' }, null, 2));
  apkZip.file('META-INF/MANIFEST.MF', 'Manifest-Version: 1.0\nCreated-By: Web2APK\n');

  const apkBuffer = await apkZip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  fs.writeFileSync(apkPath, apkBuffer);

  const defaultZip = new JSZip();
  defaultZip.file('app-release.apk', apkBuffer);
  defaultZip.file('AndroidManifest.xml', manifestXml);
  defaultZip.file(
    'README.md',
    `# Web2APK Standard Default Build\n\nThis archive contains the packaged \`app-release.apk\` and Android project assets.\nGenerated by Web2APK.\n`
  );

  const zipBuffer = await defaultZip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  fs.writeFileSync(zipPath, zipBuffer);

  console.log(`Standard default zip build created at ${zipPath}`);
}

createStandardDefaultZipBuild();
